language: python
python:
  - 3.7
  - 3.8
  - 3.9

install:
  - pip install -e .[test]
  - pip install codecov

script: py.test -v --cov=cryptoconditions && python setup.py sdist bdist_wheel && twine check dist/* 

after_success: codecov

addons:
  apt:
    packages:
    - build-essential
    - gcc
    - make
    - zsh
